%% Function generated by the Exponential distribution (non-vectorized form)

function F = func(x,y,Nmod,KMean,varK,C1,C2,phi,Nx,Ny)

S1 = zeros(Nx,Ny) ;
S2 = zeros(Nx,Ny) ;
S3 = zeros(Nx,Ny) ;
F = zeros(Nx,Ny) ;


for i = 1 : Nx
           
            for j = 1 : Ny
                    
                    S1(i,j) = sum( (-2*pi)*C1.*sin(phi + (2*pi)*(C1*x(i) + C2*y(j)))) ;
                    
                    S2(i,j) = sum( cos(phi + (2*pi)*(C1*x(i) + C2*y(j)) ) ) ;
                    
                    S3(i,j) = sum( (-2*pi)*C2.*sin(phi + (2*pi)*(C1*x(i) + C2*y(j)))) ;
              
              F(i,j) = 2*KMean*exp(-varK/2)*sqrt(varK*2/Nmod)*S1(i,j)*exp(sqrt(varK*2/Nmod)*S2(i,j))*cos(2*x(i)+y(j)) ...
                     - 5*KMean*exp(-varK/2)*exp(sqrt(varK*2/Nmod)*S2(i,j))*sin(2*x(i)+y(j)) ...
                     + KMean*exp(-varK/2)*sqrt(varK*2/Nmod)*S3(i,j)*exp(sqrt(varK*2/Nmod)*S2(i,j))*cos(2*x(i)+y(j));
              
            end
            
            
            
end


end