%% Compute the matrix generated by the function generated by the Exponential distribution (non-vectorized form)

function sol = K(x,y,Nmod,KMean,varK,C1,C2,phi,Nx,Ny)


sol = zeros(Nx,Ny) ;

coeff = sqrt(varK*2/Nmod) ;


for i = 1 : Nx
        
    for j = 1 : Ny
        
        
        sum = 0 ;
    
        
    for tt = 1 : Nmod
        
        sum = sum + cos( (C1(tt)*x(i) + C2(tt)*y(j))*(2*pi) + phi(tt)) ;
        
    end
    
        ak = coeff*sum ;
    
        sol(i,j) = KMean * exp(-varK/2) * exp(ak) ;

    end
    
end

end